### ISSUE TITLE
The OAS3 parser crashes on status code in form of a number

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/api-elements.js#157]
I'm trying to parse a minimal document and it makes the parser to emit a parser-specific failure error:

```yaml
openapi: '3.0.0'
info:
  title: Dummy API
  version: '1.0'
paths:
  /:
    get:
      responses:
        200:
          description: Index
        default:
          description: Test
```

The error:

```
{ type: 'error',
  component: 'apiDescriptionParser',
  message: 'member.key.toValue(...).match is not a function',
  location: [ [ 0, 1 ] ] }
```

The document seems to be valid according to http://editor.swagger.io/

**Comment by honzajavorek** [comment]
Using the Fury CLI, I'm able to get following stack trace:

```
TypeError: member.key.toValue(...).match is not a function
    at isStatusCode (/Users/honza/Projects/debug-fury/node_modules/fury-adapter-oas3-parser/lib/parser/oas/parseResponsesObject.js:15:31)
    at /Users/honza/Projects/debug-fury/node_modules/ramda/src/anyPass.js:44:22
    at f1 (/Users/honza/Projects/debug-fury/node_modules/ramda/src/internal/_curry1.js:18:17)
    at /Users/honza/Projects/debug-fury/node_modules/ramda/src/cond.js:47:25
    at /Users/honza/Projects/debug-fury/node_modules/ramda/src/internal/_arity.js:10:19
    at /Users/honza/Projects/debug-fury/node_modules/ramda/src/internal/_pipe.js:3:27
    at /Users/honza/Projects/debug-fury/node_modules/ramda/src/internal/_arity.js:10:19
    at transformMember (/Users/honza/Projects/debug-fury/node_modules/fury-adapter-oas3-parser/lib/parser/parseObject.js:118:32)
    at ParseResult.<anonymous> (/Users/honza/Projects/debug-fury/node_modules/minim/lib/primitives/array-element.js:341:40)
    at Array.map (<anonymous>)
```

**Comment by honzajavorek** [comment]
OK, the problem is 200 is a number and not a string. Following passes the parser:

```diff
-        200:
+        '200':
           description: Index
```

**Comment by kylef** [comment]
Note from [OpenAPI 3 Spec](https://github.com/OAI/OpenAPI-Specification/blob/39d133d34a0acae12ed66fc0a25f7ec4dc1b9391/versions/3.0.0.md#patterned-fields-1):

> This field MUST be enclosed in quotation marks (for example, "200") for compatibility between JSON and YAML.

**Comment by honzajavorek** [comment]
Wow. But OAS2 allowed this? Do we want to act strictly around this or do we want to be [benevolent](https://en.wikipedia.org/wiki/Robustness_principle), perhaps with a warning?

**Comment by pksunkara** [comment]
I think we want to be benevolent with a warning.
