### ISSUE TITLE
API B Serializer throws template render error for given document

### ISSUE THREAD

**Issue by kylef** [apiaryio/api-elements.js#315]
Using the following OpenAPI 2 document:

```yaml
swagger: '2.0'
info:
  title: Optional Parameters
  version: '1.0'
paths:
  '/test':
    get:
      parameters:
        - name: title
          in: query
          description: Body argument
          required: false
          type: array
      responses:
        200:
          description: ok
```

When converting to API Blueprint, the serializer is throwing an error

```
$ npx fury --format text/vnd.apiblueprint issue.yaml
{ Template render error: (/Users/kyle/Projects/apiaryio/api-elements.js/packages/fury-adapter-apib-serializer/template.nunjucks) [Line 1, Column 33]
  Error: Unable to call `api["attributes"]["get"]`, which is undefined or falsey
    at Object._prettifyError (/Users/kyle/Projects/apiaryio/api-elements.js/node_modules/nunjucks/src/lib.js:36:11)
    at /Users/kyle/Projects/apiaryio/api-elements.js/node_modules/nunjucks/src/environment.js:567:19
    at Template.root [as rootRenderFunc] (eval at _compile (/Users/kyle/Projects/apiaryio/api-elements.js/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:665:3)
    at Template.render (/Users/kyle/Projects/apiaryio/api-elements.js/node_modules/nunjucks/src/environment.js:556:10)
    at /Users/kyle/Projects/apiaryio/api-elements.js/node_modules/nunjucks/src/environment.js:366:27
    at createTemplate (/Users/kyle/Projects/apiaryio/api-elements.js/node_modules/nunjucks/src/environment.js:315:9)
    at handle (/Users/kyle/Projects/apiaryio/api-elements.js/node_modules/nunjucks/src/environment.js:327:11)
    at /Users/kyle/Projects/apiaryio/api-elements.js/node_modules/nunjucks/src/environment.js:339:9
    at next (/Users/kyle/Projects/apiaryio/api-elements.js/node_modules/nunjucks/src/lib.js:280:7)
    at Object.asyncIter (/Users/kyle/Projects/apiaryio/api-elements.js/node_modules/nunjucks/src/lib.js:286:3) name: 'Template render error' }
```

Repository Version: aa1101b
fury-cli 0.9.1
fury-adapter-apib-serializer 0.12.1
fury-adapter-swagger 0.27.1

**Comment by katylava** [comment]
Trying to use fury-cli 0.9.1 and running into this. When will there be a release of fury-cli that incorporates this fix?

**Comment by kylef** [comment]
Hi @katylava, I don't know for certain when the next release will be, as a workaround you can install the package from source using the following steps:

```shell
$ git clone https://github.com/apiaryio/api-elements.js.git
$ cd api-elements.js
$ yarn
$ npx fury <...>
```

This will require a pre-requsitite of installing Yarn which can be installed with `npm install -g yarn`/`brew install yarn` or similiar if you do not already have it.

**Comment by kylef** [comment]
The error is thrown when the underyling OpenAPI 2 document cannot be parsed, you can find the underlying cause to this by running `fury <path to your openapi document>` too for validation. That will prevent you having to install master:

```
$ fury --validate issue.yaml
...

error: (4) Validation failed. /paths/test/get/parameters/title is an array, so it must include an "items" schema
```

**Comment by katylava** [comment]
I think it's because my openapi schema generator didn't include responses ☹️
