### ISSUE TITLE
Template render error: Unable to call `item["value"]["toValue"]`, which is undefined or falsey

### ISSUE THREAD

**Issue by rubik** [apiaryio/api-elements.js#357]
I have an OpenAPI v3 document that I cannot convert to API Blueprint. The source document is valid, and Fury validates successfully and can convert it with the default API elements parser (`application/vnd.refract.parse-result+json`). However, if I choose API Blueprint as output, it fails both from the original OpenAPI spec and the converted API elements generated by Fury. It seems some kind of templating error that occurs when generating the markdown document:

```
$ ./fury.js -f text/vnd.apiblueprint openapi.yaml social-api.apib
Template render error: (/docs/node_modules/fury-adapter-apib-serializer/template.nunjucks) [Line 52, Column 54]
  Error: Unable to call `item["value"]["toValue"]`, which is undefined or falsey
    at Object._prettifyError (/docs/node_modules/fury-adapter-apib-serializer/node_modules/nunjucks/src/lib.js:36:11)
    at /docs/node_modules/fury-adapter-apib-serializer/node_modules/nunjucks/src/environment.js:567:19
    at Template.root [as rootRenderFunc] (eval at _compile (/docs/node_modules/fury-adapter-apib-serializer/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:665:3)
    at Template.render (/docs/node_modules/fury-adapter-apib-serializer/node_modules/nunjucks/src/environment.js:556:10)
    at /docs/node_modules/fury-adapter-apib-serializer/node_modules/nunjucks/src/environment.js:366:27
    at createTemplate (/docs/node_modules/fury-adapter-apib-serializer/node_modules/nunjucks/src/environment.js:315:9)
    at handle (/docs/node_modules/fury-adapter-apib-serializer/node_modules/nunjucks/src/environment.js:327:11)
    at /docs/node_modules/fury-adapter-apib-serializer/node_modules/nunjucks/src/environment.js:339:9
    at next (/docs/node_modules/fury-adapter-apib-serializer/node_modules/nunjucks/src/lib.js:280:7)
    at Object.asyncIter (/docs/node_modules/fury-adapter-apib-serializer/node_modules/nunjucks/src/lib.js:286:3) {
  name: 'Template render error'
}
```

Since the document is validated successfully this issue is not a duplicate of https://github.com/apiaryio/api-elements.js/issues/315

**Comment by kylef** [comment]
@rubik Are you able to share the document so we are able to reproduce? Or perhaps craft a minimal version of it removing any sensitive information. We can share over email if putting it on GitHub publically is a problem.

**Comment by rubik** [comment]
@kylef Thanks for the quick reply! I sent an email.
